[variables]
  gui = true # set to false on headless systems

[hostnames]
personal = [ "distressed-phase" ]
personal_remote = [ "greasy-gold", "brisk-falcon", "blunderbore", "overkill-1" ]
# we keep changing names! why not add ALL the names they use?
work = [ "Shauns-MacBook-Pro.local", "Mac", "Shauns-MacBook-Pro"]
